### ISSUE TITLE
NOICE

### ISSUE THREAD

**Issue by JDeepD** [adnanhasan251/HotelManagement#1]
NOICE

**Comment by Mastermind-sap** [comment]
NOICE2 @Nova-Striker @adnanhasan251

**Comment by Mastermind-sap** [comment]
#2 gud!! :rofl:  didnt know so many keywords....must admit jaydeep became GOD in this lockdown!

**Comment by subnut** [comment]
Bello!

**Comment by Mastermind-sap** [comment]
wow! is this a whatsapp grp :rofl:

**Comment by subnut** [comment]
Oi @Nova-Striker @Mastermind-sap 
Who among you two stole my project yesterday?

**Comment by subnut** [comment]
@Mastermind-sap You did?

**Comment by Mastermind-sap** [comment]
@subnut no man why will I steal your project.
I am making restaurant management system.
And yours is hotel management system. I will make my project public after I complete it you can see the logs and the project code if even a single part matches with ur code I will change my name for god sake :expressionless:

**Comment by subnut** [comment]
@Nova-Striker @adnanhasan251 Tmlog group banake project submit krega?

**Comment by Nova-Striker** [comment]
@subnut Nhi. Mai alag group mai hu

**Comment by subnut** [comment]
@Nova-Striker tum kal mera repo clone kiya tha?

**Comment by Nova-Striker** [comment]
@subnut Ha wo Vim-Smoothie reinstall ki tha

**Comment by subnut** [comment]
Nhi..... project waala repo

**Comment by Nova-Striker** [comment]
@subnut  Nhi. Project wala nhi kia

**Comment by subnut** [comment]
Kisi ne kel mera project waala repo 13 baar dekha aur phir clone bhi kiya

@adnanhasan251 tum?

**Comment by Mastermind-sap** [comment]
whatsapp grp op :laughing:

**Comment by JDeepD** [comment]
@subnut [Scroll down and see the Dragonised version](https://garudalinux.org/downloads.html)

**Comment by Mastermind-sap** [comment]
aish...one more falvour😂 @JDeepD

**Comment by subnut** [comment]
@JDeepD meh :unamused: .... Good attempt. You may like it, but I hate it. I find it too blingy. I've seen better in reddit /r/unixp*rn

**Comment by subnut** [comment]
https://www.reddit.com/r/unixporn/comments/g7vtiz/kde_plasma_moe_new_moedark_themes/

**Comment by JDeepD** [comment]
> @JDeepD meh 😒 .... Good attempt. You may like it, but I hate it. I find it too blingy. I've seen better in reddit /r/unixp*rn

Its the best I have seen after Deepin 🤣 . Ya I have seen better rices at Unixporn too but those require time to set up and thats what always keeps me away from switching distros

**Comment by Mastermind-sap** [comment]
@JDeepD bhai tum yaha flavoirs discuss kr rahe ho aur waha campus care mei ek aur maut ka farmaan aa gaya hai...math project 30th ko dena hai

**Comment by JDeepD** [comment]
@Mastermind-sap  dead

**Comment by Mastermind-sap** [comment]
already am @JDeepD

**Comment by JDeepD** [comment]
@subnut  Cant defeat this one tho 🤣🤣🤣🤣

![Screenshot 2020-11-26 134511](https://user-images.githubusercontent.com/64089730/100358225-dfaf7400-301b-11eb-8706-9ade1687377e.png)

**Comment by JDeepD** [comment]
abbey 30th sunday nhi hai kya?

**Comment by Mastermind-sap** [comment]
> @subnut Cant defeat this one tho 🤣🤣🤣🤣
> 
> ![Screenshot 2020-11-26 134511](https://user-images.githubusercontent.com/64089730/100358225-dfaf7400-301b-11eb-8706-9ade1687377e.png)

aish back on win 😂

**Comment by JDeepD** [comment]
aur ye sab bank account kya banana hai?

**Comment by Mastermind-sap** [comment]
> abbey 30th sunday nhi hai kya?

pta nhi ha shyad.😂

**Comment by JDeepD** [comment]
> aish back on win 😂

I printer does not connect to Ubuntu 😢😢😢

**Comment by Mastermind-sap** [comment]
> aur ye sab bank account kya banana hai?

wahi toh pta nhi....niche regards dekh....dis....thats what they do with our lives

**Comment by Mastermind-sap** [comment]
> > aish back on win 😂
> 
> I printer does not connect to Ubuntu 😢😢😢

😂😂😂😂prodigal son returns

**Comment by JDeepD** [comment]
ABBEY SAALE

**Comment by JDeepD** [comment]
YE KYA HAI "COPIES INCOMPLETE IN ANY ASPECT WILL NOT BE ACCEPTED"  ????

**Comment by Mastermind-sap** [comment]
> YE KYA HAI "COPIES INCOMPLETE IN ANY ASPECT WILL NOT BE ACCEPTED" ????

yeh kaha dikha?

**Comment by JDeepD** [comment]
aur krna kya hai practical mai?

**Comment by JDeepD** [comment]
wohi jo maam bheja

**Comment by Mastermind-sap** [comment]
oh pta nhi...matlab sara prac hona parega ...mene joki ek bhi nhi likha

**Comment by Mastermind-sap** [comment]
![gif](https://tenor.com/view/hungama-rajpal-yadav-maaro-humko-maro-humko-zinda-mat-chodo-saalo-gif-17920757)

**Comment by JDeepD** [comment]
[maths practical.pdf](https://github.com/adnanhasan251/HotelManagement/files/5603450/maths.practical.pdf)

Yeah boiii .

**Comment by Mastermind-sap** [comment]
kisne bheja?

**Comment by Mastermind-sap** [comment]
i will now create a repo for practicals 😂

**Comment by JDeepD** [comment]
> kisne bheja?

Black market

**Comment by Mastermind-sap** [comment]
acha...lekin likhna toh hoga hi yeh toh maam bhi de diya😅...ismei kya bari
baat hai

**Comment by subnut** [comment]
> @subnut Cant defeat this one tho :rofl: :rofl: :rofl: :rofl: :rofl:

Can, and already have.

No, I ain't gonna boot up Win10 just to show you my rice.

**Comment by JDeepD** [comment]
@subnut 😂😂😂

**Comment by subnut** [comment]
@JDeepD You don't believe me?

**Comment by JDeepD** [comment]
@Mastermind-sap  I was gonna put this under `modified push up` but then I saw it from a different angle 

![Screenshot 2020-11-26 223301](https://user-images.githubusercontent.com/64089730/100377530-6cb3f680-3037-11eb-888e-a10ed9434557.png)

**Comment by JDeepD** [comment]
@Mastermind-sap  mereko mysql ka jo likha wo bhej dena

**Comment by Mastermind-sap** [comment]
> @Mastermind-sap I was gonna put this under `modified push up` but then I saw it from a different angle
> 
> ![Screenshot 2020-11-26 223301](https://user-images.githubusercontent.com/64089730/100377530-6cb3f680-3037-11eb-888e-a10ed9434557.png)

😂😂😂

**Comment by Mastermind-sap** [comment]
> @Mastermind-sap mereko mysql ka jo likha wo bhej dena

mei kuch nhi likha...not even python

**Comment by JDeepD** [comment]
@subnut  I cannot update `subnut/vim-smoothie` using vim-plug
![Screenshot from 2020-11-29 00-10-28](https://user-images.githubusercontent.com/64089730/100523571-73796f80-31d7-11eb-9759-42a616c07cac.png)
It happened earlier also. The only fix is to completely do a Plug-Clean and Plug Install

**Comment by Mastermind-sap** [comment]
What do you use to chat?
Normal people: whatsapp and discord or even messanger
Jaydeep: github😎

**Comment by Mastermind-sap** [comment]
bhai we also have a server we can chat there also

**Comment by subnut** [comment]
@JDeepD You can rest in peace once psliwka/vim-smoothie#23 is merged

For the time being, use `Plug 'psliwka/vim-smoothie'` instead

**Comment by subnut** [comment]
@JDeepD **delete** this issue

**Comment by JDeepD** [comment]
@subnut Idk how to close an entire issue.

**Comment by JDeepD** [comment]
@subnut  [Only adnan can](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/deleting-an-issue) @adnanhasan251

**Comment by adnanhasan251** [comment]
Mai yeh sb aaj padh rha hu... :-/

**Comment by subnut** [comment]
@adnanhasan251 Delete kar issue ko

**Comment by Mastermind-sap** [comment]
@subnut itna delete krne ko kyu batawala hai?

**Comment by JDeepD** [comment]
Ahem. Hello @subnut @Mastermind-sap @adnanhasan251

**Comment by Mastermind-sap** [comment]
Yo @JDeepD
